<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/public/semantic/semantic.min.css">
    <link rel="stylesheet" href="/public/style.css">
    <title>Acesso Restrito</title>
</head>
<body>
<div class="ui sixteen column doubling stackable grid container">
    <div class="login">
        <h4>Login</h4>
        <form class="ui form">
            <div class="field">
                <label>Username</label>
                <input type="text" name="username" placeholder="Username">
            </div>
            <div class="field">
                <label>Password</label>
                <input type="text" name="password" placeholder="Password">
            </div>
            <div class="field">
                <div class="ui checkbox">
                    <input type="checkbox" tabindex="0" class="hidden" name="remember">
                    <label>Remember login</label>
                </div>
            </div>
            <button class="ui button" type="submit">Login</button>
        </form>
    </div>
</div>
</body>
</html>